config:
  atqamz_pub:cloudflareAccountId: YOUR_ACCOUNT_ID
  atqamz_pub:cloudflareZoneId: YOUR_ZONE_ID
  atqamz_pub:rootDomain: atqamz.com
  atqamz_pub:webProjectName: atqamz-web
  atqamz_pub:resumeProjectName: atqamz-resume
